# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
    
  - name: About us
    identifier: About us
    weight: 20
    
  - name: The Team
    parent: About us
    url: '#team'
    weight: 23
    
  - name: Role & Responsibilities
    parent: About us
    url: '#skills'
    weight: 25
    
  - name: Activities
    identifier: Activities
    weight: 30
  
  - name: Projects
    parent: Activities
    url: '#Project'
    weight: 33
    
  - name: Publications
    parent: Activities
    url: '#publications'
    weight: 38
    
  - name: Teaching and Training Programme
    parent: Activities
    url: '#projects'
    weight: 39
    
  - name: Lectures
    identifier: Lectures
    weight: 40
    
  - name: Blog Posts
    parent: Lectures
    url: '#posts'
    weight: 42
  - name: Classes
    parent: Lectures
    url: '#posts'
    weight: 45
    
  - name: Data Center
    identifier: Data Center
    weight: 50
    
  - name: College & Departments
    parent: Data Center
    url: 'https://debasish-pandit.shinyapps.io/EMS_SJMCH_Git/'
    weight: 52
    
  - name: Faculties
    parent: Data Center
    url: ''
    weight: 54
    
  - name: Students 
    parent: Data Center
    url:  '/Student/newpost'
    weight: 56
    
  - name: Contact
    url: '#contact'
    weight: 80


