# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: About us
    url: '#team'
    weight: 20
  - name: Posts
    url: '#posts'
    weight: 60
  - name: Projects
    url: '#Project'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 50
  - name: Teaching and Training
    url: '#projects'
    weight: 60
  - name: Lectures
    url: '#projects'
    weight: 70
  - name: Data Center
    url: '#skills'
    weight: 75
  - name: Contact
    url: '#contact'
    weight: 80

